export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body style={{
        margin: 0,
        minHeight: "100vh",
        background: "#fdf6e3",   // light parchment — warm version of #e8d5a3
        fontFamily: "Georgia, serif",
        color: "#3a2e1e",
      }}>
        {children}
      </body>
    </html>
  )
}
